insert into OPERATIONS (OPERATION_TYPE_ID, DESCRIPTION) VALUES (1, 'PURCHASE');
insert into OPERATIONS (OPERATION_TYPE_ID, DESCRIPTION) VALUES (2, 'INSTALLMENT PURCHASE');
insert into OPERATIONS (OPERATION_TYPE_ID, DESCRIPTION) VALUES (3, 'WITHDRAWAL');
insert into OPERATIONS (OPERATION_TYPE_ID, DESCRIPTION) VALUES (4, 'PAYMENT');
