-- H2 2.1.214;
SET DB_CLOSE_DELAY -1;
;
CREATE USER IF NOT EXISTS "SA" SALT '2b101447635520aa' HASH '8a0f20c3f52548e600d39b03e698914d4ffd0c0c8f62cbaceb45f2c9173ace69' ADMIN;
CREATE SEQUENCE "PUBLIC"."ACCOUNTS_SEQ" START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."TRANSACTIONS_SEQ" START WITH 1 INCREMENT BY 50;
CREATE MEMORY TABLE "PUBLIC"."ACCOUNTS"(
    "ACCOUNT_ID" BIGINT NOT NULL,
    "DOCUMENT_NUMBER" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."ACCOUNTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ACCOUNT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT;
CREATE MEMORY TABLE "PUBLIC"."OPERATIONS"(
    "OPERATION_TYPE_ID" INTEGER NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."OPERATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("OPERATION_TYPE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OPERATION;
CREATE MEMORY TABLE "PUBLIC"."TRANSACTIONS"(
    "TRANSACTION_ID" BIGINT NOT NULL,
    "ACCOUNT_ID" BIGINT,
    "AMOUNT" NUMERIC(38, 2),
    "EVENT_DATE" TIMESTAMP(6),
    "OPERATION_TYPE_ID" INTEGER
);
ALTER TABLE "PUBLIC"."TRANSACTIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("TRANSACTION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTION;
ALTER TABLE "PUBLIC"."ACCOUNTS" ADD CONSTRAINT "PUBLIC"."UK_HR89I0J2Q08S9TM3F6SEK3HNQ" UNIQUE("DOCUMENT_NUMBER");
